FROM golang:1.21 AS build
WORKDIR /chaincode

# go.sum is intentionally NOT copied/relied upon here. It was generated by
# hand in an offline sandbox and could not be verified against the real Go
# module proxy, so it is more likely to be wrong than helpful. `go mod tidy`
# resolves every dependency (including fabric-chaincode-go's exact
# pseudo-version) freshly, inside this container, which has real internet
# access and full write permissions — unlike the VPS shell user and unlike
# the sandbox that originally authored these files.
COPY go.mod ./
RUN go mod tidy

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /chaincode-server .

FROM debian:bookworm-slim
COPY --from=build /chaincode-server /chaincode-server
EXPOSE 9999
CMD ["/chaincode-server"]